[package]
name = "sdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
float-cmp = "0.9.0"
nalgebra = "0.27.1"
bevy = "0.6"
rand = "0.8"
